AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: qk.run
Globals:
  Api:
    BinaryMediaTypes:
    - '*/*'
Resources:
  QkRunFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://gabipurcarudotcom/eee885a5e372118cbdf7f48d08a7686a
      Handler: DUMMY
      Runtime: provided
      MemorySize: 128
      Events:
        Web:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WebRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
